/*
 * © 2024 AO Kaspersky Lab
 * Licensed under the 3-Clause BSD License
 */

package example.IConsumer

const UInt16 MaxMessageSize = 1024;
typedef sequence<SInt8, MaxMessageSize> Message;

interface
{
    Consume(in Message message);
}
